# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update latest post

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          envkey_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          envkey_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          envkey_APP_ID: ${{ secrets.APP_ID }}
          directory: /
          file_name: .env
      - run: npm run update-post
